{% set name = "pymt_overland_flow" %}
{% set version = "0.1" %}
{% set build = "0" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  path: ..

build:
  number: {{ build }}
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  host:
    - python
    - setuptools
    - numpy 1.11.*
    - cython
    - model_metadata
    - landlab 

  run:
    - python
    - setuptools
    - pymt
    - landlab 

test:
  requires:
    - bmi-tester
    - model_metadata
  imports:
    - pymt
    - pymt_overland_flow
  commands:
    - config_file=$(mmd-stage OverlandFlow . > MANIFEST && mmd-query OverlandFlow --var=run.config_file.path)
    - bmi-test pymt_overland_flow.bmi:OverlandFlow --infile=$config_file --manifest=MANIFEST -v

about:
  summary: Python package that wraps the overland_flow BMI.
  home: https://github.com/mcflugen/pymt_overland_flow
  license: MIT license
  license_file: LICENSE
  dev_url: https://github.com/mcflugen/pymt_overland_flow
